### ISSUE TITLE
Add important client metrics

### ISSUE THREAD

**Issue by alvin-reyes** [application-research/delta-metrics-rest#4]
```[tasklist]
### Tasks
- [ ] Onboarded data per SP
- [ ] Onboarded data per User
- [ ] Onboarded data per Delta instance
- [ ] Onboarded data per Client
```
