### ISSUE TITLE
Timeseries stats

### ISSUE THREAD

**Issue by alvin-reyes** [application-research/delta-metrics-rest#5]
```[tasklist]
### Tasks
- [ ] Time-series deal stats (daily, weekly, monthly, date range)
- [ ] Time-series e2e deal stats (daily, weekly, monthly, date range)
- [ ] Time-series import deal stats (daily, weekly, monthly, date range)
- [ ] Time-series commp deal stats (daily, weekly, monthly, date range)
```
